/*
** EPITECH PROJECT, 2024
** R-Type
** File description:
** ServerStatus
*/

enum class ServerStatus {
    WAITING_FOR_CREATE_ENTITY,
    WAITING_FOR_CREATE_INPUT,
    WAITING_FOR_CREATE_RECTANGLE_SHAPE,
    WAITING_FOR_CREATE_ONCLICK,
    WAITING_FOR_CREATE_TEXT,
};
